name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main and gh-pages
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Chart
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          helm package . --version $VERSION --app-version $VERSION
          CHART_FILE=$(ls *.tgz)
          echo "Packaged: $CHART_FILE"

      - name: Update repository
        run: |
          # Копируем chart в gh-pages директорию
          cp *.tgz gh-pages/
          
          # Переходим в gh-pages и обновляем index
          cd gh-pages
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          
          # Коммитим и пушим изменения
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add chart version ${{ github.ref_name }}"
          git push origin gh-pages
