name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Chart
        run: |
          cd main
          VERSION=${GITHUB_REF#refs/tags/v}
          helm package . --version $VERSION --app-version $VERSION
          echo "Packaged chart:"
          ls -la *.tgz

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update repository
        run: |
          # Копируем chart из main в gh-pages
          cp main/*.tgz gh-pages/
          
          # Обновляем index в gh-pages
          cd gh-pages
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          
          echo "Files in gh-pages:"
          ls -la
          echo "Index contents:"
          cat index.yaml

      - name: Commit and push
        run: |
          cd gh-pages
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add chart version ${{ github.ref_name }}"
          git push origin gh-pages
